#!/bin/bash

# InsureTrack Environment Variables Setup Script
# This script helps you set up environment variables for Vercel deployment

echo "🚀 InsureTrack Environment Variables Setup"
echo "=========================================="

echo ""
echo "📋 Frontend Environment Variables (mavrix-insurance)"
echo "---------------------------------------------------"
echo "Go to: https://vercel.com/dashboard"
echo "Select: mavrix-insurance project"
echo "Navigate: Settings → Environment Variables"
echo ""
echo "Add these variables:"
echo "REACT_APP_API_URL=https://mavrix-insurance-api.vercel.app"
echo "REACT_APP_ENVIRONMENT=production"
echo "REACT_APP_VERSION=1.0.0"
echo ""

echo "🔧 Backend Environment Variables (mavrix-insurance-api)"
echo "-----------------------------------------------------"
echo "Go to: https://vercel.com/dashboard"
echo "Select: mavrix-insurance-api project"
echo "Navigate: Settings → Environment Variables"
echo ""
echo "Required variables:"
echo "NODE_ENV=production"
echo ""
echo "Optional variables (for MongoDB):"
echo "MONGODB_URI=mongodb+srv://your-username:your-password@your-cluster.mongodb.net/insuretrack"
echo "DATABASE_NAME=insuretrack"
echo ""
echo "Optional variables (for email):"
echo "EMAIL_USER=your-email@gmail.com"
echo "EMAIL_PASSWORD=your-app-password"
echo "SMTP_HOST=smtp.gmail.com"
echo "SMTP_PORT=587"
echo ""
echo "Optional variables (for configuration):"
echo "REMINDER_DAYS=7"
echo ""

echo "🔗 Production URLs"
echo "------------------"
echo "Frontend: https://mavrix-insurance.vercel.app"
echo "API: https://mavrix-insurance-api.vercel.app"
echo "API Health: https://mavrix-insurance-api.vercel.app/api/health"
echo ""

echo "✅ Setup Complete!"
echo "Remember to redeploy your projects after adding environment variables."
